// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL_EF.Entities
{
    public partial class Role
    {
        public int IdRole { get; set; }
        public string RoleName { get; set; }
    }
}