// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL_EF.Entities
{
    public partial class Step
    {
        public Step()
        {
            AttachmentSteps = new HashSet<AttachmentStep>();
            Todos = new HashSet<Todo>();
        }

        public int IdStep { get; set; }
        public int IdTrip { get; set; }
        public string Name { get; set; }
        public int? Budget { get; set; }
        public decimal? Time { get; set; }
        public string Comments { get; set; }

        public virtual Trip IdTripNavigation { get; set; }
        public virtual ICollection<AttachmentStep> AttachmentSteps { get; set; }
        public virtual ICollection<Todo> Todos { get; set; }
    }
}