// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL_EF.Entities
{
    public partial class Todo
    {
        public Todo()
        {
            AttachmentTodos = new HashSet<AttachmentTodo>();
            InverseIdMainTodoNavigation = new HashSet<Todo>();
        }

        public int IdTodo { get; set; }
        public int IdStep { get; set; }
        public int? IdMainTodo { get; set; }
        public string Name { get; set; }
        public bool Done { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string Priority { get; set; }
        public DateTime? Calendar { get; set; }
        public string Location { get; set; }
        public decimal? PlannedTime { get; set; }
        public int? PlannedBudget { get; set; }
        public decimal? RealTime { get; set; }
        public int? RealBudget { get; set; }
        public string Comments { get; set; }

        public virtual Todo IdMainTodoNavigation { get; set; }
        public virtual Step IdStepNavigation { get; set; }
        public virtual ICollection<AttachmentTodo> AttachmentTodos { get; set; }
        public virtual ICollection<Todo> InverseIdMainTodoNavigation { get; set; }
    }
}