// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL_EF.Entities
{
    public partial class Trip
    {
        public Trip()
        {
            AttachmentTrips = new HashSet<AttachmentTrip>();
            Steps = new HashSet<Step>();
        }

        public int IdTrip { get; set; }
        public string Name { get; set; }
        public DateTime StartingDate { get; set; }
        public DateTime EndingDate { get; set; }
        public int? Budget { get; set; }
        public string Comments { get; set; }
        public int IdUser { get; set; }

        public virtual User IdUserNavigation { get; set; }
        public virtual ICollection<AttachmentTrip> AttachmentTrips { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
    }
}