// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL_EF.Entities
{
    public partial class User
    {
        public User()
        {
            Trips = new HashSet<Trip>();
        }

        public int IdUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }

        public virtual ICollection<Trip> Trips { get; set; }
    }
}